---
- name: Check if Helm is installed
  ansible.builtin.command: helm version --short
  register: helm_check
  changed_when: false
  failed_when: false

- name: Install Helm 3
  ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash
  when: helm_check.rc != 0
