#!/usr/bin/env python3
"""Build Ansible inventory from terraform output JSON (stdin)."""

from __future__ import annotations

import json
import os
import sys


def talos_mode() -> bool:
    env = os.environ.get("TALOS_ENABLED", "").lower()
    return env in ("true", "1", "yes")


def main() -> int:
    data = json.load(sys.stdin)
    talos = talos_mode()

    if talos:
        lb = data.get("talos_lb", {}).get("value")
        leaders = data.get("talos_controlplane_nodes", {}).get("value") or []
        workers = data.get("talos_worker_nodes", {}).get("value") or []
    else:
        lb = data.get("k8s_lb", {}).get("value")
        leaders = data.get("k8s_leader_nodes", {}).get("value") or []
        workers = data.get("k8s_worker_nodes", {}).get("value") or []

    ssh_user = os.environ.get("SSH_USER", "root")
    k3s_token = os.environ.get("K3S_TOKEN", "")
    ssh_key = os.environ.get("ANSIBLE_SSH_PRIVATE_KEY_FILE", "")

    env_id = data.get("env_id", {}).get("value") or os.environ.get("ENV_ID", "homelab")

    if not lb:
        print("error: load balancer output missing (lb_enabled=false?)", file=sys.stderr)
        return 1
    if not leaders:
        print("error: no control plane / leader nodes in terraform output", file=sys.stderr)
        return 1

    k3s_server_url = lb["api_url"]
    lb_ip = lb["ip"]
    first_leader_url = f"https://{leaders[0]['ip']}:6443"

    tailscale = data.get("tailscale", {}).get("value") or {}

    lines: list[str] = [
        "# Generated by scripts/generate-inventory.sh — do not edit by hand.",
        "all:",
        "  vars:",
        f"    ansible_user: {ssh_user}",
        "    ansible_become: true",
        f"    env_id: \"{env_id}\"",
        f"    k3s_server_url: \"{k3s_server_url}\"",
        f"    k3s_lb_ip: \"{lb_ip}\"",
        f"    k3s_first_leader_url: \"{first_leader_url}\"",
        f"    talos_enabled: {str(talos).lower()}",
    ]

    if talos:
        lines.append(f"    talos_api_url: \"{k3s_server_url}\"")

    if tailscale:
        lines += [
            f"    tailscale_proxy_tag: \"{tailscale['proxy_tag']}\"",
            f"    homelab_network_cidr: \"{tailscale['homelab_network_cidr']}\"",
            f"    tailscale_connector_name: \"{tailscale['connector_name']}\"",
            f"    tailscale_connector_hostname: \"{tailscale['connector_hostname']}\"",
        ]

    if not talos and k3s_token:
        lines.append(f"    k3s_token: \"{k3s_token}\"")
    if ssh_key:
        lines.append(f"    ansible_ssh_private_key_file: \"{ssh_key}\"")

    if not talos:
        k3s_version = os.environ.get("K3S_VERSION", "")
        if k3s_version:
            lines.append(f"    k3s_version: \"{k3s_version}\"")

    lines.append("  children:")

    lines += [
        "    k8s_lb:",
        "      hosts:",
        f"        {lb['name']}:",
        f"          ansible_host: {lb['ip']}",
    ]

    if talos:
        lines += ["    talos_controlplane:", "      hosts:"]
        for node in leaders:
            lines += [
                f"        {node['name']}:",
                f"          ansible_host: {node['ip']}",
            ]
        if workers:
            lines += ["    talos_workers:", "      hosts:"]
            for node in workers:
                lines += [
                    f"        {node['name']}:",
                    f"          ansible_host: {node['ip']}",
                ]
    else:
        first = leaders[0]
        lines += [
            "    k3s_first_leader:",
            "      hosts:",
            f"        {first['name']}:",
            f"          ansible_host: {first['ip']}",
        ]

        if len(leaders) > 1:
            lines += ["    k3s_additional_leaders:", "      hosts:"]
            for node in leaders[1:]:
                lines += [
                    f"        {node['name']}:",
                    f"          ansible_host: {node['ip']}",
                ]

        if workers:
            lines += ["    k3s_workers:", "      hosts:"]
            for node in workers:
                lines += [
                    f"        {node['name']}:",
                    f"          ansible_host: {node['ip']}",
                ]

    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
